version: '3'

services:
    database:
        build: ./db
        restart: always
        volumes:
            - ./db/workdir:/var/lib/mysql
        expose:
            - "80"
        networks:
            - backend-network
        environment:
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_USER: "ask"
            MYSQL_PASSWORD: "123"
            MYSQL_DATABASE: "inmarket_db"
    node:
        build: .
        volumes:
            - .:/usr/app
            - /usr/app/node_modules
        expose:
            - "80"
        networks:
            - backend-network
            - proxy-network
        command: npm start
        depends_on:
            - database
    nginx:
        image: nginx:stable
        container_name: production_nginx
        depends_on:
            - node
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/mime.types:/etc/nginx/mime.types
            # - ./nginx/error.log:/etc/nginx/error_log.log
            - ./nginx/cache/:/etc/nginx/cache
            - ./nginx/www:/usr/share/nginx/inmarket/html
            # - /etc/letsencrypt/:/etc/letsencrypt/
        ports:
            - 80:80
            - 443:443
        networks:
            - proxy-network
networks:
    backend-network:
    proxy-network:
