version: '3'

services:
    database:
        build: ./db
        restart: always
        volumes:
            - ./db/workdir:/var/lib/mysql
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_USER: "ask"
            MYSQL_PASSWORD: "123"
            MYSQL_DATABASE: "inmarket_db"
    webserver:
        build: .
        volumes:
            - .:/srv/http/node
        ports:
            - 5000:5000
            - 9229:9229
        command: npm start
        depends_on:
            - database
