-- MySQL Script generated by MySQL Workbench
-- Sun 20 Jan 2019 08:09:26 PM CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema inmarket_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema inmarket_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `inmarket_db` DEFAULT CHARACTER SET utf8 ;
USE `inmarket_db` ;

-- -----------------------------------------------------
-- Table `inmarket_db`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inmarket_db`.`user` ;

CREATE TABLE IF NOT EXISTS `inmarket_db`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `kommuneNr` INT NOT NULL,
  `adminLevel` INT NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `profilePicture` VARCHAR(100) NULL,
  `createTime` DATETIME NOT NULL,
  `emailVerified` TINYINT(1) NOT NULL DEFAULT 0,
  `biography` TEXT(500) NULL,
  `userType` INT(1) NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inmarket_db`.`student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inmarket_db`.`student` ;

CREATE TABLE IF NOT EXISTS `inmarket_db`.`student` (
  `user_id` INT NOT NULL,
  `school` VARCHAR(45) NOT NULL,
  `schoolYear` VARCHAR(45) NOT NULL,
  `program` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`user_id`),
  INDEX `fk_student_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_student_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `inmarket_db`.`user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `inmarket_db`.`company`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inmarket_db`.`company` ;

CREATE TABLE IF NOT EXISTS `inmarket_db`.`company` (
  `user_id` INT NOT NULL,
  `description` TEXT(1000) NULL,
  `logo` VARCHAR(45) NULL,
  `tags` VARCHAR(100) NULL,
  `verifiedCompany` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`user_id`),
  CONSTRAINT `fk_company_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `inmarket_db`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inmarket_db`.`conversation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inmarket_db`.`conversation` ;

CREATE TABLE IF NOT EXISTS `inmarket_db`.`conversation` (
  `conversation_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`conversation_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inmarket_db`.`message`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inmarket_db`.`message` ;

CREATE TABLE IF NOT EXISTS `inmarket_db`.`message` (
  `message_id` INT NOT NULL AUTO_INCREMENT,
  `conversation_id` INT NOT NULL,
  `sender` INT NOT NULL,
  `content` TEXT(500) NOT NULL,
  `timestamp` INT(11) UNSIGNED NOT NULL,
  PRIMARY KEY (`message_id`, `conversation_id`, `sender`),
  INDEX `fk_message_conversation1_idx` (`conversation_id` ASC),
  INDEX `fk_message_user1_idx` (`sender` ASC),
  CONSTRAINT `fk_message_conversation1`
    FOREIGN KEY (`conversation_id`)
    REFERENCES `inmarket_db`.`conversation` (`conversation_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_message_user1`
    FOREIGN KEY (`sender`)
    REFERENCES `inmarket_db`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inmarket_db`.`conversationParticipants`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inmarket_db`.`conversationParticipants` ;

CREATE TABLE IF NOT EXISTS `inmarket_db`.`conversationParticipants` (
  `user_id` INT NOT NULL,
  `conversation_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `conversation_id`),
  INDEX `fk_conversationParticipants_conversation1_idx` (`conversation_id` ASC),
  CONSTRAINT `fk_conversationParticipants_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `inmarket_db`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_conversationParticipants_conversation1`
    FOREIGN KEY (`conversation_id`)
    REFERENCES `inmarket_db`.`conversation` (`conversation_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inmarket_db`.`userFile`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inmarket_db`.`userFile` ;

CREATE TABLE IF NOT EXISTS `inmarket_db`.`userFile` (
  `userFile_id` INT NOT NULL AUTO_INCREMENT,
  `path` VARCHAR(100) NOT NULL,
  `description` VARCHAR(45) NULL,
  `user_id` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`userFile_id`),
  INDEX `fk_userFile_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_userFile_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `inmarket_db`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inmarket_db`.`activity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inmarket_db`.`activity` ;

CREATE TABLE IF NOT EXISTS `inmarket_db`.`activity` (
  `activity_id` INT NOT NULL AUTO_INCREMENT,
  `startTime` TIMESTAMP(6) NOT NULL,
  `endTime` TIMESTAMP(6) NULL,
  `user_id` INT NOT NULL,
  `company_user_id` INT NOT NULL,
  PRIMARY KEY (`activity_id`),
  INDEX `fk_activity_user1_idx` (`user_id` ASC),
  INDEX `fk_activity_company1_idx` (`company_user_id` ASC),
  CONSTRAINT `fk_activity_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `inmarket_db`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_activity_company1`
    FOREIGN KEY (`company_user_id`)
    REFERENCES `inmarket_db`.`company` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inmarket_db`.`employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inmarket_db`.`employee` ;

CREATE TABLE IF NOT EXISTS `inmarket_db`.`employee` (
  `user_id` INT NOT NULL,
  `position` VARCHAR(45) NULL,
  `verifiedEmployee` TINYINT(1) NOT NULL DEFAULT 0,
  `company_user_id` INT NOT NULL,
  PRIMARY KEY (`user_id`),
  INDEX `fk_employee_company1_idx` (`company_user_id` ASC),
  CONSTRAINT `fk_employee_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `inmarket_db`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employee_company1`
    FOREIGN KEY (`company_user_id`)
    REFERENCES `inmarket_db`.`company` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inmarket_db`.`contact`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inmarket_db`.`contact` ;

CREATE TABLE IF NOT EXISTS `inmarket_db`.`contact` (
  `user1_id` INT NOT NULL,
  `user2_id` INT NOT NULL,
  PRIMARY KEY (`user1_id`, `user2_id`),
  INDEX `fk_contact_user2_idx` (`user2_id` ASC),
  CONSTRAINT `fk_contact_user1`
    FOREIGN KEY (`user1_id`)
    REFERENCES `inmarket_db`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contact_user2`
    FOREIGN KEY (`user2_id`)
    REFERENCES `inmarket_db`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inmarket_db`.`jobseeker`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inmarket_db`.`jobseeker` ;

CREATE TABLE IF NOT EXISTS `inmarket_db`.`jobseeker` (
  `user_id` INT NOT NULL,
  PRIMARY KEY (`user_id`),
  CONSTRAINT `fk_table1_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `inmarket_db`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inmarket_db`.`contactRequest`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inmarket_db`.`contactRequest` ;

CREATE TABLE IF NOT EXISTS `inmarket_db`.`contactRequest` (
  `sender_id` INT NOT NULL,
  `receiver_id` INT NOT NULL,
  PRIMARY KEY (`sender_id`, `receiver_id`),
  INDEX `fk_contactRequest_user2_idx` (`receiver_id` ASC),
  CONSTRAINT `fk_contactRequest_user1`
    FOREIGN KEY (`sender_id`)
    REFERENCES `inmarket_db`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contactRequest_user2`
    FOREIGN KEY (`receiver_id`)
    REFERENCES `inmarket_db`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
